[tool.poetry]
name = "gt-crops-helper"
version = "0.0.1"
description = "Tool for manage crops from IC2, Gregtech mods"
authors = ["Artem 'artctv' <artctvcode@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.2.2"
pysimplegui = "^5.0.8"


[tool.poetry.group.dev.dependencies]
psgcompiler = "^5.0.0"
pyvis = "^0.3.2"
openpyxl = "^3.1.5"
watchfiles = "^1.0.4"
jupyterlab = "^4.3.4"
pandas = "^2.2.3"
lxml = "^5.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
